### ISSUE TITLE
Important URLs in documentation are not valid!!

### ISSUE THREAD

**Issue by farshidalpha** [coreos/updateservicectl#84]
Reading instructions from:

https://github.com/coreos/updateservicectl/blob/master/Documentation/example-container-update.md 

I noticed that some of the links that are essential to get updateservicectl to work properly refer to the main document page and not the correct ones. 

Examples: 
 example update repository
 Zero Downtime Frontend Deploys with Vulcand

Thanks

**Comment by stilliard** [comment]
example-container-update.md would still be a very useful page, also there is still a link to it in the main README file.

**Comment by sym3tri** [comment]
@stilliard Thanks for the feedback. The docs were incomplete & incorrect so they were probably more misleading than helpful. That's why we decided to remove them for now until we have time to revise them or come up with a more generalized approach.

Custom update solutions will require custom code to speak the Omaha Protocol. So I'd refer you to the protocol docs here: https://github.com/coreos/updateservicectl/blob/master/Documentation/protocol.md

**Comment by stilliard** [comment]
Thanks for the reply @sym3tri, I'll look into the Omaha protocol a bit more. 
But in my case, all my apps are up on docker hub so I guess the simplest method is to have a timer that runs daily, pulls down the latest versions of the images and restarts the services. 
I was just looking for that document in case there were any suggestions around this method, or any reasons it wouldn't work well.
